language: ruby
rvm:
  - 2.1.0
  - 2.0.0
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email:
    recipients:
      - "scott.turnbull@aptrust.org"
    on_success: "change"
    on_failure: "always"
# Whitelist of branches to build
branches:
  only:
    - master
    - develop
