language: ruby
rvm:
  - 2.1.0
  - 2.0.0
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - secure: XHjeFTlHHhdwdZfV6HzvCfovU2fRVPO3Uc7tBAHa8MRXPGaphxfvcJU4HSrDouWKemm/9As67NNocwKkLdyQ920spQ4+DJdnDnz0ifY7oLz98DBBoniXhtpaJQ1ahCl6l7754Rt5U6XNeHT71K4t5GSm4hrjHpq7mJpgRY6BzUs=
    - secure: ZBCss4Cr2QNh0lN3JcCCZkqU3AORpnRKVZP0WEjZIJdYnxeuirkZ3IdLgYL6dUVpt1/mv5bXD19UJh6TA5JNb3fN+Kx30jXVIUVBBYqU6iHqE6yV6a3rC4QJgCob1IlZStJ9QxBNWo5nwEpEgrfJbz8s7extrYTQNq3GB2AR9a0=
notifications:
  email:
    recipients:
      - "scott.turnbull@aptrust.org"
      - "kelly.croswell@aptrust.org"
      - "andrew.diamond@aptrust.org"
    on_success: "change"
    on_failure: "always"
branches:
  only:
    - master
    - develop
before_install:
  - gem install bundler
before_script:
  - bundle exec rake db:migrate RAILS_ENV=test

