development: 
  user: <%= ENV['FEDORA_USER'] %>
  password: <%= ENV['FEDORA_PASS'] %>
  url: <%= ENV['FEDORA_URL'] %>
demo:
  user: <%= ENV['FEDORA_USER'] %>
  password: <%= ENV['FEDORA_PASS'] %>
  url: <%= ENV['FEDORA_URL'] %>
test: &TEST  
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/fedora-test" %>
production:
  user: <%= ENV['FEDORA_USER'] %>
  password: <%= ENV['FEDORA_PASS'] %>
  url: <%= ENV['FEDORA_URL'] %>
cucumber:
  <<: *TEST
