uva-only:
  - uva-only
archivist:
  - archivist1@example.com
donor:
  - donor1@example.com
researcher:
  - researcher1@example.com
patron:
  - patron1@example.com
admin_policy_object_editor:
  - archivist1@example.com
admin:
  - kelly.croswell@aptrust.org
institutional_admin:

institutional_user:

1admin:

1user:

2admin:

2user:

3admin:

3user:

4admin:

4user:

5admin:

5user:

6admin:

6user:

7admin:

7user:

8admin:

8user:

9admin:

9user:

10admin:

10user:

11admin:

11user:


